### ISSUE TITLE
DISCUSSION: Front-end technologies

### ISSUE THREAD

**Issue by ThomasLuu00** [ThomasLuu00/RecipeBook#8]
We will be making requests from DjangoREST API. Therefore, we should be able to use any framework we want. Initially I was just planning to embed Vue into the Django pages but we can go with whatever we are comfortable with for the front-end since we are just calling from the back-end.  Comment what you would prefer to work with for this project.

**Comment by musickiper** [comment]
I have knowledge on React and Angular. I prefer to use Angular recently, but, I can use React as well.

**Comment by ThomasLuu00** [comment]
I have mostly used React but I'm honestly open to any framework, even vanilla JS.  @Immutablevoid how about you?

**Comment by Immutablevoid** [comment]
Doesn't matter to me

**Comment by ThomasLuu00** [comment]
Okay then lets try something new and use Vue.  This will be a good learning opportunity for us. I will close this issue unless anyone wants something else.

**Comment by ThomasLuu00** [comment]
Actually, might just be better to be more comfortable with development an not overload ourselves with research, so let's use Angular instead of Vue.

**Comment by james-jung-ysj** [comment]
Good

**Comment by ashn01** [comment]
Great, I am currently using Angular

**Comment by ThomasLuu00** [comment]
Alright, Angular it is then!
