### ISSUE TITLE
DISCUSSION: Wrap everything in a docker container

### ISSUE THREAD

**Issue by ThomasLuu00** [ThomasLuu00/RecipeBook#9]
Would be nice to put this project into a Docker container.  I have zero experience with this and I am also unsure if it will be necessary for this project.  If anyone has experience with this then please provide some insight. If not, this will require some more research to determine if its appropriate.

**Comment by musickiper** [comment]
I know the basic stuff of Docker and Kubernetes. But, as you mentioned, I am not sure if we need to use these things or not.

**Comment by ThomasLuu00** [comment]
Will it be easy to just put everything into a docker container once we are done with the full-stack?

**Comment by james-jung-ysj** [comment]
We can make 3 containers for (back-end API, front-end client, proxy server), and can manage them using Kubernetes. I think it will be better than just putting everything inside one container.

**Comment by ThomasLuu00** [comment]
Okay, that makes sense.  @ashn01 @Immutablevoid do you guys agree with this approach?

**Comment by Immutablevoid** [comment]
Also doesn't matter to me 👍. I'm down for anything

**Comment by ashn01** [comment]
I agree
